databases:
  hosts:
    Microsql01:
      ansible_host: 0.0.0.0 #IP HOST Primairos
  vars:
    ansible_user: ansible_adm
    ansible_password: Password # Agregar password
    ansible_winrm_server_cert_validation: ignore
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_install_fts: true
    mssql_install_powershell: true
    mssql_tune_for_fua_storage: true
